name: base

on:
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version tag
        run: |
          ./scripts/version_tag >> $GITHUB_ENV

      - name: Build and push amd64 image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/terrat/Dockerfile.consolidated
          push: true
          target: build-base
          tags: |
            ghcr.io/${{ github.repository_owner }}/terrat-base:${{ env.VERSION_TAG }}-amd64

  build-arm64:
    runs-on: ubuntu-24.04-arm64
    environment: production

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version tag
        run: |
          ./scripts/version_tag >> $GITHUB_ENV

      - name: Build and push arm64 image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/terrat/Dockerfile.consolidated
          push: true
          target: build-base
          tags: |
            ghcr.io/${{ github.repository_owner }}/terrat-base:${{ env.VERSION_TAG }}-arm64

  create-manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: write
      packages: write
      id-token: write

    env:
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      GITHUB_REF: ${{ github.ref }}
      TERRATEAM_ENVIRONMENT: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version tag
        run: |
          ./scripts/version_tag >> $GITHUB_ENV

      - name: Create and push multi-arch manifest
        run: |
          ./scripts/create_manifest terrat-base
