name: code-indexer-build-production

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        TERRATEAM_SELF_HOSTED_BUILD_GH_TOKEN: ${{ secrets.TERRATEAM_SELF_HOSTED_BUILD_GH_TOKEN }}
      run: |
        curl -L https://fly.io/install.sh | sh
        /home/runner/.fly/bin/flyctl auth docker
        docker pull registry.fly.io/terrateam-app-production:base
        docker build -t "ghcr.io/terrateamio/terrat-code-indexer:latest" --build-arg BASE_IMAGE="registry.fly.io/terrateam-app-production:base" -f docker/terrat/Dockerfile.code_indexer .
        docker push "ghcr.io/terrateamio/terrat-code-indexer:latest"
