name: Deploy Docs to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        env:
          VERCEL_DEPLOY_URL: ${{ secrets.VERCEL_DEPLOY_URL }}
        run: |
          curl -X POST "$VERCEL_DEPLOY_URL"
