name: 'system-tests'

on:
  workflow_dispatch:
    inputs:
      action-branch:
        required: true
        default: 'main'
        description: 'terrateam action branch'
      repo-url:
        required: true
        default: 'git@github.com:terrateam-test/terraform.git'
        description: 'repo url for tests'
      default-branch:
        required: true
        default: 'main'
        description: 'default branch of repo url'
      tests:
        required: false
        default: ''
        description: 'specify tests or leave empty for all'
      terrateam-base-build:
        required: true
        type: boolean
        default: 'false'
        description: 'docker build terrateam-base instead of docker pull'
      terrateam-build:
        required: true
        type: boolean
        default: 'true'
        description: 'docker build terrateam instead of docker pull'

jobs:
  tests:
    runs-on: self-hosted
    timeout-minutes: 2880
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      env:
        DOCKER_BUILDKIT: 1
        AGE_IDENTITY_PATH: "/tmp/.age.key"
        DEBIAN_FRONTEND: "noninteractive"
        MATRIX_PASSWORD: ${{ secrets.MATRIX_PASSWORD }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GH_TOKEN: ${{ secrets.TERRATEAM_TEST_ADMIN_01_GH_TOKEN }}
        AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        TERRATEAM_BASE_BUILD: ${{ github.event.inputs.terrateam-base-build }}
        TERRATEAM_BUILD: ${{ github.event.inputs.terrateam-build }}
      run: |
        cd tests/terrat/system-tests
        mkdir -p ${{ runner.temp }}/test-output
        make start
        make -k TEST_OUTPUT_DIR=${{ runner.temp }}/test-output TERRATEAM_BASE_BUILD=${{ github.event.inputs.terrateam-base-build }} REPO_URL=${{ github.event.inputs.repo-url }} DEFAULT_BRANCH=${{ github.event.inputs.default-branch }} AGE_IDENTITY_PATH=${AGE_IDENTITY_PATH} FORCE_BUILD_BASE=${{ github.event.inputs.terrateam-base-build }} ${{ github.event.inputs.tests }}
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        output: '${{ runner.temp }}/test-summary.md'
        paths: |
          ${{ runner.temp }}/test-output/**/*.tap
      if: always()
    - name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: ${{ runner.temp }}/
      if: always()
